In [8]:
import json
import pandas as pd

with open("./database/series.json","r",encoding="utf-8") as series:
    datos = json.load(series)

datos[5:10]

df_movies = pd.read_csv("./database/movies.csv")
df_channels = pd.read_csv("./database/channels.csv")

In [9]:
df_movies

,title,genre,classification,duration,synopsis,url
0,El transportador 3,Action & Adventure,PG-13,1hr 43 min,Frank Martin es un indiscutible especialista e...,https://pluto.tv/on-demand/movies/5e6a42b4e2fa...
1,Operación Condor - La Armadura de Dios 2,Action & Adventure,TV-14,1hr 47 min,"Jackie, un talentoso cazador de tesoros, es co...",https://pluto.tv/on-demand/movies/5fa95cd39d99...
2,Until Death,Action & Adventure,R,1hr 46 min,Jean-Claude Van Damme interpreta a un teniente...,https://pluto.tv/on-demand/movies/5e9da6c03f93...
3,Tráfico Humano,Action & Adventure,R,1hr 37 min,"Traumatizado por la muerte de un inocente, Bra...",https://pluto.tv/on-demand/movies/62bf189b5a39...
4,Badges of Fury,Crime,R,1hr 38 min,Una ola de asesinatos sacude Hong Kong. El jov...,https://pluto.tv/on-demand/movies/5eaaeb0d718b...
...,...,...,...,...,...,...
1851,The Assassins,Drama,R,1hr 47 min,"Durante finales de la dinastía Han del Este, e...",https://pluto.tv/on-demand/movies/5eaaeb08718b...
1852,Relaciones Exteriores,Drama,PG,1hr 32 min,"Harry Raymond, embajador de Canadá en Moscú, e...",https://pluto.tv/on-demand/movies/6399e7c2eb85...
1853,1911,Documentary,R,1hr 39 min,La historia se centra en el nacimiento de la R...,https://pluto.tv/on-demand/movies/5f3fd87aad19...
1854,El Regreso de Joe May,Drama,R,1hr 47 min,Joe May es un estafador envejecido que se afer...,https://pluto.tv/on-demand/movies/62bf021cd972...
1855,Pequeños Accidentes,Drama,R,1hr 44 min,En una pequeña comunidad conmocionada por un a...,https://pluto.tv/on-demand/movies/60bf725bd782...

In [10]:
print(f"Hay un total de {len(df_movies)} peliculas y un total de {len(df_movies["genre"].unique())} generos")

Hay un total de 1856 peliculas y un total de 22 generos

In [11]:
df_channels.sample(5)

,Nombre_Canal,Url_Canal
22,Pluto TV Cine Romance,https://pluto.tv/live-tv/5dcdde78f080d90009855...
34,MTV Ridiculousness,https://pluto.tv/live-tv/646ccdd0939a5900088a1...
46,Sin Tetas No Hay Paraíso,https://pluto.tv/live-tv/6474a7e7f77b6100080a8...
18,Pluto TV España,https://pluto.tv/live-tv/5dcb62e63d4d8f0009f36...
19,Vive Kanal D Drama,https://pluto.tv/live-tv/64ff270f30ab3300084e2...

In [12]:
print(f"Hay un total de {len(df_channels)} canales ")

Hay un total de 53 canales

In [13]:
df_serie = pd.DataFrame(columns=['title',"genre","classification","synopsis","temporadas"
                                 ,"url"])
for serie in datos:
    df_serie.loc[len(df_serie)] = [serie["title"],serie["genre"],serie["classification"],serie["synopsis"],len(serie["seasons"]),serie["url"]]
    

df_serie

,title,genre,classification,synopsis,temporadas,url
0,Cumbres Borrascosas,Drama,PG-13,"Basada en la novela de Emily Brontë, Wuthering...",1,https://pluto.tv/on-demand/series/65ce5d04a3a8...
1,Prueba de FE,Telenovela,TV-PG,En cada capítulo de esta serie se narra uno de...,1,https://pluto.tv/on-demand/series/5e46e3bc033f...
2,Escándalos,Telenovela,TV-14,"Serie de unitarios que narra en ficción,famoso...",1,https://pluto.tv/on-demand/series/5e4abd1d9e43...
3,Solamente Milagros,Telenovela,TV-14,Cuenta historias inspiradas en hechos reales y...,3,https://pluto.tv/on-demand/series/60589aaef3fd...
4,La Ronca de Oro,Drama,TV-PG,"Helena Vargas, queriendo ser libre en una époc...",1,https://pluto.tv/on-demand/series/65085ab0f64f...
...,...,...,...,...,...,...
206,Jobs,Documentary,PG-13,"En 1976, Steve Jobs, que había dejado de estud...",1,https://pluto.tv/on-demand/series/5eb171b0d6ea...
207,Juan Pablo II,Drama,PG,Los acontecimientos más importantes de la vida...,1,https://pluto.tv/on-demand/series/65ce5affd6d7...
208,Lugares Oscuros,Thriller,R,La historia de una mujer que sobrevivió al bru...,1,https://pluto.tv/on-demand/series/66c4aca36134...
209,El Rescate de una Vida,Drama,PG-13,Un vagabundo gentil y destrozado es obligado p...,1,https://pluto.tv/on-demand/series/5e0e6044a6cb...
210,"KISNA, EL POETA GUERRERO",Drama,PG,Kisna se ha comprometido a llevar a Katherine ...,1,https://pluto.tv/on-demand/series/63a0b784eb85...

In [14]:
print(f"Hay un total de {len(df_serie)} series con {len(df_serie["genre"].unique())} generos")


max_temporadas = int(df_serie["temporadas"].idxmax())
min_temporadas = int(df_serie["temporadas"].idxmin())
print(f"La serie con mayor cantidad de temporadas es {df_serie.iloc[max_temporadas]["title"]} con {df_serie.iloc[max_temporadas]["temporadas"]} temporadas" )

Hay un total de 211 series con 18 generos
La serie con mayor cantidad de temporadas es South Park con 25 temporadas

In [15]:

episodios = pd.DataFrame(columns=['title', 'season', 'number_of_episodes'])

for serie in datos:
    title = serie["title"]  
    for temporada in serie["seasons"]:
        season = temporada["season"]  
        number_of_episodes = len(temporada["episodes"])

        nueva_fila = pd.DataFrame({
            'title': [title],
            'season': [season],
            'number_of_episodes': [number_of_episodes]
        })

        episodios = pd.concat([episodios, nueva_fila], ignore_index=True)


episodios

                        title    season number_of_episodes
0         Cumbres Borrascosas  Season 1                  5
1                Prueba de FE  Season 1                 15
2                  Escándalos  Season 1                 45
3          Solamente Milagros  Season 1                 20
4          Solamente Milagros  Season 2                 18
..                        ...       ...                ...
407                      Jobs  Season 1                  1
408             Juan Pablo II  Season 1                  2
409           Lugares Oscuros  Season 1                  1
410    El Rescate de una Vida  Season 1                  1
411  KISNA, EL POETA GUERRERO  Season 1                  1

[412 rows x 3 columns]

### Top 10 series con mas episodios

In [20]:
episodios.groupby("title")["number_of_episodes"].sum().reset_index().sort_values(by='number_of_episodes',ascending=False).head(10)

                              title number_of_episodes
10                Archivos Forenses                376
139                      South Park                294
164                       Yu-Gi-Oh!                234
134  Sin tetas no hay paraíso (ESP)                225
109                          Naruto                220
12               Autopista al Cielo                220
82            La Familia del Barrio                188
67                         Inuyasha                167
90      Lo Que Callamos Las Mujeres                160
101                        MacGyver                139